### ISSUE TITLE
Python 3.7.9 compatible?

### ISSUE THREAD

**Issue by suesauer** [1xinghuan/usdNodeGraph#11]
Hey, was trying a USD build with python 3.7.9, all went well with Usdview. But the Maya plugin didn't work any more with the new Maya 2021 beta pr release 118. It says that ufe.getStage() module doesn't exist(import ufe works just fine). 
Not sure if you have access to the maya beta, but thought I would give you a heads up. The nodeGraph works perfectly for me in maya 2021/python2.7 tho.

**Comment by 1xinghuan** [comment]
Sorry I don't have access to maya beta. Maybe in maya 2021 there's a new way to get stage from a node. You can get an answer in maya forum I guess.

**Comment by suesauer** [comment]
cool cool

**Comment by TechArtistG** [comment]
I ran 2to3 to convert the entire lib to Python 3 and seems to work fine for me in Maya 2021 PR121 with USD 0.6
