### ISSUE TITLE
missing addNodeCallback

### ISSUE THREAD

**Issue by suesauer** [1xinghuan/usdNodeGraph#6]
Hey there,

Cloned down your repo today 8/24/2020.

When I run from usdNodeGraph.api import addNodeCallback in Maya 2020.2 using USD 20.08. It says: 

`import usdNodeGraph.ui.nodeGraph as usdNodeGraph
from usdNodeGraph.api import addNodeCallback
#Error: ImportError: file <maya console> line 20: cannot import name addNodeCallback # `

I tried to manually find addNodeCallback but cant find it in the repo. Has this been removed?

Thanks for cool little tool
Sue

**Comment by 1xinghuan** [comment]
Sorry for that issue.
I need to add a branch 'dev' and put all internal changes into that branch, also fix errors on 'master'.
I will do it soon.

**Comment by 1xinghuan** [comment]
You can download the latest master branch and test.
Thank you~

**Comment by suesauer** [comment]
thanks will do 👍
